version: '3.8'

services:
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
    networks:
      - spring-demo

  # API service
  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres  # You can keep this here if using a local Postgres for development
    environment:
      DB_HOST: dpg-cu1q9hrtq21c73bk9r7g-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_NAME: ebook_86j1
      DB_USERNAME: zoro
      DB_PASSWORD: R49F0vgaUz9X9VSuoYBlPW3BYyTtRLGv
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_APPLICATION_NAME: DVD-Library

  # UI service
  bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - bsn-api

networks:
  spring-demo:
    driver: bridge

# No need to configure local volumes for Render; remove this section if not needed.
volumes:
  postgres:
    driver: local
