spring:
  datasource:
    url: jdbc:postgresql://dpg-cu1q9hrtq21c73bk9r7g-a.oregon-postgres.render.com/ebook_86j1
    username: zoro
    password: R49F0vgaUz9X9VSuoYBlPW3BYyTtRLGv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: adithya7887@gmail.com
    password: pqmfwohnluglhysr
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    #      connectiontimeout: 5000
    #      timeout: 3000
    #      writetimeout: 5000
    protocol: smtp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://8888-2409-4072-6e9e-9971-606c-89f4-5bf2-e17f.ngrok-free.app/realms/e-books"
application:
  file:
    upload:
      photos-output-path: ./uploads

server:
  port: 8088
