spring:
  datasource:
    url: jdbc:postgresql://dpg-cu1q9hrtq21c73bk9r7g-a.oregon-postgres.render.com:5432/ebook_86j1
    username: zoro
    password: R49F0vgaUz9X9VSuoYBlPW3BYyTtRLGv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME}  # Use environment variables for sensitive data
    password: ${MAIL_PASSWORD}  # Use environment variables for sensitive data
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://keycloak-bsn.onrender.com/realms/e-books"  # Update to Render's Keycloak instance
application:
  file:
    upload:
      photos-output-path: /app/uploads  # Update file path for Render

server:
  port: 8088
